### ISSUE TITLE
Getting Uncaught Error: Mismatched anonymous define() module: [object Object]

### ISSUE THREAD

**Issue by seroth77** [fedoranimus/aurelia-gojs#1]
I am getting this error when I try to load the project. I removed all gojs code and traced it all the way back to the aurelia.json file. When I remove the gojs dependency (while all gojs code is commented out) Aurelia loads as intended. When I add it back the error occurs. 

I am using gojs lastest version in npm

**Comment by fedoranimus** [comment]
Okay - Aurelia and GoJS have changed a bit since I put together this project. I'll take a look this weekend.

**Comment by jmdavid** [comment]
I just tested with updated version of gojs (^1.8.15) and everything is fine.

**Comment by seroth77** [comment]
Not sure what I'm doing wrong then because the error is consistent

**Comment by jmdavid** [comment]
No but I use Webpack, not JSPM.

**Comment by seroth77** [comment]
I use straight CLI with npm. I don't use jspm or webpack.

**Comment by fedoranimus** [comment]
@seroth77 Are you loading any other libraries via script tags? Have you modified this repo in any way?

**Comment by seroth77** [comment]
No, I have not. Au new setup my base project and then npm install gojs
--save.  Then au build.

**Comment by fedoranimus** [comment]
Have you modified your aurelia.json to include and name gojs? 

https://github.com/fedoranimus/aurelia-gojs/blob/master/aurelia_project/aurelia.json#L130

I just tested (and updated every package to the latest version) this repo and it works fine.

**Comment by seroth77** [comment]
Yes, I added it to look exactly like his example

**Comment by seroth77** [comment]
I found the issue, https://stackoverflow.com/questions/49451227/gojs-and-aurelia-mismatch-error. This solution works great for anyone who uses webpack as it resolves the issue but if it's just requirejs ppl with get the error. That is what I was using. After implementing this change, everything worked great. This bug can be marked as closed and anyone with this issue can use the stackoverflow method to resolve their issue. Thanks for looking into it.
